Repository aladdinsys/survey_backend, pull requests merged in 2024-02, with the labels that each got.

#8 Feature/set thymeleaf
  src/main/java/aladdinsys/aladdin_survey/domains/auth/service/AuthenticationService.java
  src/main/java/aladdinsys/aladdin_survey/domains/survey/controller/SurveyController.java
  src/main/java/aladdinsys/aladdin_survey/domains/survey/dto/SurveyResponse.java
  src/main/java/aladdinsys/aladdin_survey/domains/survey/entity/Survey.java
  src/main/java/aladdinsys/aladdin_survey/domains/survey/repository/SurveyRepository.java
  src/main/java/aladdinsys/aladdin_survey/domains/survey/service/SurveyService.java
  src/main/java/aladdinsys/aladdin_survey/global/config/SecurityConfig.java
  src/main/java/aladdinsys/aladdin_survey/global/controller/OpenApiController.java
  src/main/java/aladdinsys/aladdin_survey/global/controller/ViewController.java
  src/main/java/aladdinsys/aladdin_survey/global/security/JwtAuthenticationFilter.java
  src/main/resources/application.yaml
  src/main/resources/static/favicon.ico
  src/main/resources/static/js/common/api.js
  src/main/resources/static/js/common/auth.js
  src/main/resources/static/js/contents/survey.js
  src/main/resources/static/libs/aladdin-survey/aladdin-survey.css
  src/main/resources/static/libs/aladdin-survey/aladdin-survey.iife.js
  src/main/resources/static/style/common/reset.css
  src/main/resources/static/style/contents/survey.css
  src/main/resources/templates/contents/survey.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/layouts/layout.html
  src/test/java/aladdinsys/aladdin_survey/domains/survey/service/SurveyServiceTest.java
Labels: feature

#9 타임리프 제거 및 시큐리티 컨피그 수정
  build.gradle
  src/main/java/aladdinsys/aladdin_survey/domains/auth/controller/AuthenticationController.java
  src/main/java/aladdinsys/aladdin_survey/global/constant/ExtractPath.java
  src/main/java/aladdinsys/aladdin_survey/global/controller/ViewController.java
  src/main/java/aladdinsys/aladdin_survey/global/security/JwtAuthenticationFilter.java
  src/main/resources/static/favicon.ico
  src/main/resources/static/js/common/api.js
  src/main/resources/static/js/common/auth.js
  src/main/resources/static/js/contents/survey.js
  src/main/resources/static/libs/aladdin-survey/aladdin-survey.css
  src/main/resources/static/libs/aladdin-survey/aladdin-survey.iife.js
  src/main/resources/static/style/common/reset.css
  src/main/resources/static/style/contents/survey.css
  src/main/resources/templates/contents/survey.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/layouts/layout.html
Labels: feature, enhancement

#13 Test: 에러 처리 관련 테스트 코드 작성
  src/main/java/aladdinsys/aladdin_survey/domains/survey/controller/SurveyController.java
  src/main/java/aladdinsys/aladdin_survey/global/config/SwaggerConfig.java
  src/test/java/aladdinsys/aladdin_survey/domains/survey/controller/SurveyControllerTest.java
Labels: enhancement
